config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/home', to: 'home#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'
  # Then my current page should be "/dashboard"
  resources :users, only: [:new, :create]

  get '/dashboard', to: 'users#show', as: 'user'
  get '/shipping', to: 'users#edit', as: 'edit_user'
  patch '/shipping', to: 'users#update', as: 'update_user'
  get '/confirmation', to: 'carts#confirm', as: 'confirmation'

  resources :items, only: [:index, :show]

  put '/cart/remove', :to => 'carts#remove'

  resource :cart, only: [:show, :create, :update]

  resources :orders, only: [:create, :index, :show, :update]

  namespace :admin do
    get '/dashboard', to: "users#admin_dash"
    get '/dashboard/analytics', to: "users#analytics"
    resources :users, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :create, :index, :edit, :update]
  end

  match '/send_report', via: :post, to: "admin/users#sales_report"


  resources :reviews, only: [:create, :destroy]




















  #STAY DOWN
  get "/:category_name", to: "categories#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def price_format(number = price)
    "$%.2f" % number
  end
end

app/models/cart.rb
class Cart

  attr_reader :contents

  def initialize(initial_contents)
     @contents = initial_contents || {}
  end

  def add_item(item_id)
    contents[item_id.to_s] ||= 0
    contents[item_id.to_s] += 1
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_items
  has_many :items, through: :category_items

  validates :name, presence: true
end

app/models/category_item.rb
class CategoryItem < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :category_items
  has_many :categories, through: :category_items
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :reviews

  validates :price, presence: true, :numericality => {greater_than: 0}
  validates :description, presence: true
  validates :title, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :items, through: :order_items
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :first_name, :last_name, :role, :password_digest, :email, presence: true
  validates :email, uniqueness: true

  has_many :orders
  has_many :reviews

  enum role: %w(default admin)

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <link href="carousel.css" rel="stylesheet">
  </head>

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <div class="first-slide"> <%= image_tag('mcclures_jar.jpg') %> </div>
          <div class="container">
            <div class="carousel-caption">
              <h1>Are you a member?</h1>
              <p>Become a pro pickler today and sign up for full access to all of the finest pickles.</p>
              <p><a class="btn btn-lg btn-primary" href="/users/new" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="second-slide"> <%= image_tag('vampire_dill.jpg') %> </div>
          <div class="container">
            <div class="carousel-caption">
              <h1>Pickles for all!</h1>
              <p>Every kind of pickle product your heart could desire. See all pickled products by clicking the button below.</p>
              <p><a class="btn btn-lg btn-primary" href="/items" role="button">Check 'em out</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="third-slide"> <%= image_tag('pickle_pile.jpg') %> </div>
          <div class="container">
            <div class="carousel-caption">
              <h1>All pickles. All day.</h1>
              <p>Nothing but the best for a pickle fanatic such as yourself.</p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

    <br><br>

    <div class="container marketing">
      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-4">
          <h2 class="featurette-heading">The Doctor is in. And he smells like pickles.</h2>
          <p class="lead">The esteemed Dr. Picklemeister has been providing the finest pickles to the public since 1968. He's extensively traveled the country, and the world, to hand pick the absolute best selection of picklery. Now, his collection is available online for you to enjoy.</p>
        </div>
        <div class="col-md-5 col-md-pull-6">
          <%= image_tag('picklemeister2.jpg', :class => "img-circle", width: 250) %>
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->

    </div><!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "We Can Pickle That" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    
    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-inverse bg-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/home">WeCanPickleThat</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "All Pickles", items_path %></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <% Category.all.each do |category| %>
                  <li>
                    <%= link_to category.name, "/#{category.name}" %>
                  </li>
                  <% end %>
                </ul>
              </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user && current_user.admin? %>
              <li class=dropdown>
                <%= render partial: 'shared/admin_dash_path' %>
              </li>
            <% end %>
            <% if current_user %>
              <%= render partial: 'shared/default_user_path' unless current_user.admin? %>
              <%= render partial: 'shared/admin_user_path' if current_user.admin? %>
              <li><%= link_to logout_path, method: :delete do %><span class="glyphicon glyphicon-log-out"></span> Logout</a></li><% end %>
            <% else %>
              <li><%= link_to new_user_path do %><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <% end %>
              <li><%= link_to login_path do %><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
              <% end %>
            <% end %>
            <li><%= link_to cart_path do %>
              View Cart
              <span class="glyphicon glyphicon-shopping-cart"></span>
            <% end %></li>
        </ul>
        </div>
      </div>
    </div>


    <div class="container main-content">
      <% flash.each do |name, msg| %>
      <div class="alert fade in alert-<%= name %> ">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <%= sanitize(msg) %>
      </div>
      <% end %>
      <div class="row">
        <div class="col-lg-12">
          </div>
          <div class="well">
            <%= yield %>
          </div>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

  </body>
  <div class="footer">
    <p>&copy; WePickledIt 2017</p>
  </div>
</html>